alter session set current_schema=bank;
SET heading OFF;
SELECT ACCOUNT_NO, TRANS_AMT
FROM BANK_SB_ACCOUNT , BANK_TRANSACTION 
WHERE ACCOUNT_NO = TRANS_ACC_NO
AND (TRANS_AMT = 6700 OR TRANS_AMT = 19011.54) AND TRANS_TYPE = 'DB';
