alter session set current_schema=bank;
SET heading OFF;
SELECT CUST_ID, CUST_PHONE, CUST_ADDR_LINE1, CUST_ADDR_LINE2, CUST_CITY, CUST_STATE, CUST_PIN
FROM BANK_CUST_CONTACT
WHERE CONTACT_TYPE = 'HOME' AND CUST_STATE="Karnataka" OR CUST_STATE="Tamilnadu"
