alter session set current_schema=bank;
SET heading OFF;
SELECT TRANS_DT,LOWER(SUBSTR(TRANS_DESC,1,20)) AS TRANS_DESC,TRANS_AMT
FROM BANK_TRANSACTION
WHERE TRANS_TYPE LIKE '%CR%' AND TO_CHAR(TRANS_DT,'MM-YYYY') = '06-2010';
