alter session set current_schema=bank;
SET heading OFF;
SELECT TRANS_DT, TRANS_ACC_NO, TRANS_DESC, TRANS_AMT,
CASE 
	WHEN TRANS_TYPE = 'CR' THEN 'Credit'
	ELSE 'Debit'
END AS "TRANS_TYPE"
FROM BANK_TRANSACTION
WHERE TRANS_AMT > 10000 AND TRANS_DESC NOT LIKE 'RD INST%' 
ORDER BY TRANS_TYPE, TRANS_DT DESC;
