alter session set current_schema=bank;
SET heading OFF;

SELECT ACCOUNT_NO, CUST_ID, ROUND(INITIAL_AMT/100000, 2) AS "INITIALAMTIN_LAKHS",
CASE
	WHEN INITIAL_AMT < 50000 THEN 'Low'
	WHEN INITIAL_AMT > 5000000 THEN 'High'
	ELSE 'Medium'
END AS "AMOUNT_CATEGORY",START_DT, ADD_MONTHS(START_DT, FD_TERM_MNTH) AS "MATURITY_DATE"
FROM BANK_FD_ACCOUNT
WHERE TO_CHAR(START_DT, 'YYYY') > 2004 AND UPPER(ACC_STATUS) = 'ACTIVE';
